#!/usr/bin/php
<?php
	chdir(dirname($argv[0]));
	require("../libraries/configuration.php");

	if (($argv[1] != "for") || ($argv[2] != "sure")) {
		exit("Are you 'for sure'?\n");
	}

	$db = new MySQLi_connection(DB_HOSTNAME, DB_DATABASE, DB_USERNAME, DB_PASSWORD);
	if ($db->connected == false) {
		exit("Internal error: database not available.\n");
	}
	
	$tables = array("host_statistics", "cgi_statistics",
		"server_statistics" "events", "hostnames", "webservers");
	foreach ($tables as $table) {
		$query = "truncate table %S";
		$db->query($query, $table);
	}
?>
