#!/usr/bin/php
<?php
	chdir(dirname($argv[0]));
	require("../libraries/banshee.php");

	function validate_setting($db, $key, $type, $value) {
		if ($db->entry("settings", $key, "key") != false) {
			return true;
		}

		$entry = array(
			"key"   => $key,
			"type"  => $type,
			"value" => $value);
		return $db->insert("settings", $entry) !== false;
	}

	$db = new MySQLi_connection(DB_HOSTNAME, DB_DATABASE, DB_USERNAME, DB_PASSWORD);
	if ($db->connected == false) {
		exit("Internal error: database not available.\n");
	}

	validate_setting($db, "hiawatha_cache_enabled", "boolean", "false");
	validate_setting($db, "session_timeout", "integer", "3600");
	validate_setting($db, "session_persistent", "boolean", "false");
?>
